//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoAPE2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("proyectoAPE2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _450_1000 {
            get {
                object obj = ResourceManager.GetObject("450_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _450_10001 {
            get {
                object obj = ResourceManager.GetObject("450_10001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _611yiKn8AVL__AC_UF894_1000_QL80_ {
            get {
                object obj = ResourceManager.GetObject("611yiKn8AVL._AC_UF894,1000_QL80_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _64e79ca5aff2fb7295bfddf9_github_que_es {
            get {
                object obj = ResourceManager.GetObject("64e79ca5aff2fb7295bfddf9_github-que-es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7c4a5a5ee7b7e5955007391b2ce55665 {
            get {
                object obj = ResourceManager.GetObject("7c4a5a5ee7b7e5955007391b2ce55665", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _86731045_fondo_abstracto_geométrico_blanco_y_gris_con_las_líneas_plantilla_para_páginas_web_folletos {
            get {
                object obj = ResourceManager.GetObject("86731045-fondo-abstracto-geométrico-blanco-y-gris-con-las-líneas-plantilla-para-p" +
                        "áginas-web-folletos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_06_a_las_18_53_29_31fce292 {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-06 a las 18.53.29_31fce292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_06_a_las_18_53_29_fc1c78a2 {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-06 a las 18.53.29_fc1c78a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_06_a_las_18_54_36_301a5bfd {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-06 a las 18.54.36_301a5bfd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_06_a_las_18_54_37_45156aa7 {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-06 a las 18.54.37_45156aa7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_09_a_las_22_26_20_19e542cf {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-09 a las 22.26.20_19e542cf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_09_a_las_22_27_00_09216849 {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-09 a las 22.27.00_09216849", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_09_a_las_22_28_38_60d6d523 {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-09 a las 22.28.38_60d6d523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2025_04_09_a_las_22_29_16_a4ede6ca {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2025-04-09 a las 22.29.16_a4ede6ca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1394876713_640x640 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1394876713-640x640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MC___Bienvenida {
            get {
                object obj = ResourceManager.GetObject("MC - Bienvenida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_cleaning_computer_icons_cleaner_housekeeping_others_white_smiley {
            get {
                object obj = ResourceManager.GetObject("png-clipart-cleaning-computer-icons-cleaner-housekeeping-others-white-smiley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
